// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuzwbcfvifwxzutvytrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1endiY2Z2aWZ3eHp1dHZ5dHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3NDMwNDAsImV4cCI6MjA1MjMxOTA0MH0.l_zKVFbjLl4nzpIrSxoyexW1-wIUKlLl3J-uCzy08nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);